// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  znodeApiUrl: 'http://localhost:44762',
  znodeAdminUrl: 'http://localhost:6766',
  znodeAdminApiResourcePrefix: '/angularadminpoc/',
  znodeWebStoreApiUrl: 'http://localhost:3288',
  znodeWebStoreApiResources: [ // all resources fetched from Znode are assumed to be on API (ex: 44762),
                               // unless on this list and assumed to be on WebStore (ex: 3288)
    'angularpoc/bannerslider',
    'headeritems'
  ],
  znodeWebStoreApiCacheablePosts: [ // all GET requests to Znode are assumed to be cacheable,
                                    // POSTs can also be cached by adding to this list
    'search/fulltextsearch'
  ],
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
  storeSettings: {
    catelogId: 3
  },
  znodeUserId: 2
};
